[package]
name = "micro-gui"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Run Linux GUI applications directly inside a terminal"

[dependencies]
ctrlc = { version = "3.5.2", features = ["termination"] }
crossterm = "0.29.0"
memmap2 = "0.9.11"
nix = { version = "0.31.3", features = ["process", "signal"] }
x11rb = { version = "0.14.0", features = ["damage", "image", "shm", "xtest"] }
xkeysym = "0.2.1"
